/* Operator console. All money and case states come from the server ledger. */
'use strict';
const $ = s => document.querySelector(s);
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = p => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format((p||0)/100);
const names = {payment_failure:'Payment failures',checkout_abandoned:'Abandoned checkouts',overdue_receivable:'Overdue invoices',subscription_failure:'Failed subscriptions'};
let data=null, source='', activeCase='', busy=false, pollTimer=null, token=sessionStorage.getItem('recovery-token')||'', lastReading='', proposalId=null;
const labels={overview:'Control room',campaigns:'Recovery cases',lab:'Batch lab',evidence:'Evidence & controls',connections:'Connections',messages:'Messages'};
function notice(text,error=false){$('#notice').hidden=!text;$('#notice').textContent=text;$('#notice').classList.toggle('error',error)}
async function api(path,options={}){const r=await fetch(path,{...options,headers:{'X-Recovery-Client':'console',...(token?{'Authorization':'Bearer '+token}:{}),...(options.body?{'Content-Type':'application/json'}:{}),...options.headers}});if(!r.ok){let e;try{e=await r.json()}catch{e={detail:'The server did not return a valid response'}}throw Error(typeof e.detail==='string'?e.detail:JSON.stringify(e.detail))}return r}
async function json(path,options){return (await api(path,options)).json()}
function page(id){document.querySelectorAll('.page').forEach(e=>e.hidden=e.id!=='page-'+id);document.querySelectorAll('.nav').forEach(e=>e.classList.toggle('active',e.dataset.page===id));$('#crumb').textContent=labels[id];window.scrollTo({top:0});if(id==='messages')loadMessages()}
document.querySelectorAll('[data-page]').forEach(e=>e.onclick=()=>page(e.dataset.page));document.querySelectorAll('[data-go]').forEach(e=>e.onclick=()=>page(e.dataset.go));
function badge(state){const tone=state==='RECOVERED'?'green-badge':['ESCALATED','OPTED_OUT','EXHAUSTED','HALTED'].includes(state)?'amber':'';return `<span class="badge ${tone}">${esc(state.replaceAll('_',' '))}</span>`}
async function refreshStatus(){const state=await json('/api/status');$('#connection').textContent='Engine connected';const selected=source;$('#source').innerHTML='<option value="">Select a batch</option><option value="live">Razorpay test ledger</option>'+state.jobs.filter(j=>j.status==='complete').map(j=>`<option value="${esc(j.id)}">${esc(j.kind||'Simulated batch')} · ${j.total_cases||j.config.n} cases · ${esc(j.created.slice(0,16).replace('T',' '))}</option>`).join('');$('#source').value=selected;$('#capabilities').innerHTML=[['Razorpay test credentials',state.razorpay?'Configured':'Not configured'],['AI reply interpretation',state.ai.length?state.ai.join(', '):'Unavailable · human review fallback'],['Verified webhook endpoint',state.webhook?'Configured':'Set webhook secret'],['Signed customer links',state.customer_links?'Configured':'Set token secret']].map(([a,b])=>`<div class="capability"><span>${esc(a)}</span><span>${esc(b)}</span></div>`).join('');const running=state.jobs.find(j=>['queued','running'].includes(j.status));if(running){busy=true;setProgress(running);schedulePoll(running.id)}else if(!source){const completed=state.jobs.find(j=>j.status==='complete');if(completed){source=completed.id;$('#source').value=source}}return state}
async function refresh(){try{renderAccount(await refreshStatus());if(source)await load();notice('')}catch(e){notice(e.message,true);$('#connection').textContent='Connection needs attention'}}
async function load(){if(!source)return;data=await json('/api/snapshot?source='+encodeURIComponent(source));$('#empty').hidden=true;$('#overview-data').hidden=false;$('#mode').textContent=data.job?.kind||data.mode;$('#updated').textContent='Ledger as of '+new Date(data.at).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'});$('#case-count').textContent=data.metrics.cases;const m=data.metrics;$('#m-recovered').textContent=money(m.recovered);$('#m-risk').textContent=money(m.at_risk);$('#m-won').textContent=m.won+' paid cases reconciled';$('#m-cases').textContent=m.cases+' campaigns opened';$('#m-rate').textContent=m.cases?(m.won/m.cases*100).toFixed(1)+'%':'—';$('#m-open').textContent=m.open;$('#m-contacts').textContent=m.contacts+' contact attempts';drawChart();renderStreams();renderCases();renderReview();renderChecks()}
$('#source').onchange=async()=>{source=$('#source').value;if(!source)return;try{await load();notice('')}catch(e){notice(e.message,true)}};$('#refresh').onclick=refresh;
function drawChart(){const series=data.daily;const width=620,height=210,left=62,right=16,top=20,bottom=36;let total=0;const points=series.map(([d,v])=>[d,total+=v]);const max=Math.max(total,100);const x=i=>left+(width-left-right)*i/Math.max(points.length-1,1);const y=v=>height-bottom-(height-top-bottom)*v/max;let svg='';for(let i=0;i<=3;i++){const v=max*i/3;svg+=`<line x1="${left}" y1="${y(v)}" x2="${width-right}" y2="${y(v)}" stroke="#2b3730" stroke-dasharray="3 5"/><text x="${left-10}" y="${y(v)+3}" text-anchor="end">${esc(money(v))}</text>`}if(points.length){const line=points.map((p,i)=>(i?'L':'M')+x(i)+','+y(p[1])).join(' ');svg+=`<defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#b7f598" stop-opacity=".2"/><stop offset="100%" stop-color="#b7f598" stop-opacity="0"/></linearGradient></defs><path d="${line} L${x(points.length-1)},${height-bottom} L${left},${height-bottom} Z" fill="url(#area)"/><path d="${line}" stroke="#b7f598" stroke-width="2.5" fill="none"/>`;points.forEach(([d,v],i)=>{svg+=`<circle cx="${x(i)}" cy="${y(v)}" r="3" fill="#b7f598"><title>${esc(d)}: ${esc(money(v))}</title></circle>`;if(i%Math.max(1,Math.ceil(points.length/5))===0||i===points.length-1)svg+=`<text x="${x(i)}" y="${height-10}" text-anchor="middle">${esc(d.slice(5))}</text>`})}else svg+=`<text x="340" y="110" text-anchor="middle">No reconciled payments yet</text>`;$('#chart').innerHTML=`<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Cumulative recovery ${esc(money(total))}">${svg}</svg>`}
function renderStreams(){$('#streams').innerHTML=Object.entries(names).map(([kind,title],i)=>{const s=data.streams.find(s=>s.kind===kind)||{cases:0,exposure:0,recovered:0};const rate=s.exposure?s.recovered/s.exposure*100:0;return `<button class="stream" data-kind="${kind}"><div class="stream-top"><span>0${i+1} /</span><span>${s.cases} cases ↗</span></div><h3>${title}</h3><strong>${money(s.recovered)}</strong><small>recovered of ${money(s.exposure)}</small><div class="bar"><i style="width:${Math.min(rate,100)}%"></i></div></button>`}).join('');$('#streams').querySelectorAll('button').forEach(e=>e.onclick=()=>{$('#kind-filter').value=e.dataset.kind;page('campaigns');renderCases()})}
function renderCases(){if(!data)return;const term=$('#search').value.toLowerCase(),state=$('#state-filter').value,kind=$('#kind-filter').value;const rows=data.campaigns.filter(c=>(!state||c.state===state)&&(!kind||c.kind===kind)&&(!term||(c.reference+' '+c.classification).toLowerCase().includes(term)));$('#cases').innerHTML=rows.map(c=>`<tr><td><button class="ref-button" data-ref="${esc(c.reference)}">${esc(c.reference)}<small>${esc(names[c.kind]||c.kind)}</small></button></td><td>${esc(c.classification.replaceAll('_',' '))}</td><td class="amount">${money(c.amount)}</td><td class="amount ${c.recovered?'green':''}">${c.recovered?money(c.recovered):'—'}</td><td>${badge(c.state)}</td><td><button class="text-button" data-ref="${esc(c.reference)}">Inspect ↗</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty-line">No cases match these filters.</td></tr>';$('#table-count').textContent=`${rows.length} of ${data.campaigns.length} campaigns · ${data.events.toLocaleString()} ledger events`;bindRefs($('#cases'))}
['#search','#state-filter','#kind-filter'].forEach(id=>$(id).addEventListener('input',renderCases));
function bindRefs(node){node.querySelectorAll('[data-ref]').forEach(e=>e.onclick=()=>openCase(e.dataset.ref))}
function renderReview(){$('#review-count').textContent=data.review.length+' OPEN';$('#review-list').innerHTML=data.review.slice(0,5).map(r=>`<div class="review-row"><div><button class="ref-button" data-ref="${esc(r.reference)}">${esc(r.reference)}</button><small>${esc(r.decline_class)} · ${esc(r.stop_reason.replaceAll('_',' '))}</small></div><span>${money(r.at_risk_paise)}</span><button class="text-button resolve" data-ref-resolve="${esc(r.reference)}">Resolve →</button></div>`).join('')||'<div class="empty-line">No unresolved handoffs in this cohort.</div>';bindRefs($('#review-list'));$('#review-list').querySelectorAll('.resolve').forEach(e=>e.onclick=async()=>{const note=prompt('Resolution note (campaign remains stopped):');if(!note)return;try{await json(`/api/cases/${encodeURIComponent(e.dataset.refResolve)}/resolve?source=${encodeURIComponent(source)}`,{method:'POST',body:JSON.stringify({note})});await load()}catch(err){notice(err.message,true)}})}
function renderChecks(){$('#checks').innerHTML=data.evidence.length?data.evidence.map(c=>`<article class="check"><span class="check-icon">${c.passed?'✓':'!'}</span><b>${esc(c.name)}</b><span class="badge ${c.passed?'green-badge':'red-badge'}">${c.passed?'PASSED':'NEEDS ATTENTION'}</span><p class="caption">${esc(c.detail)}</p></article>`).join(''):'<article class="check"><b>No batch verification attached</b><p>Run a simulated batch to evaluate its ledger invariants. Operational records can be exported for inspection.</p></article>'}
async function openCase(reference){try{const detail=await json(`/api/cases/${encodeURIComponent(reference)}?source=${encodeURIComponent(source)}`);activeCase=reference;lastReading='';renderCaseMessages(detail);const c=detail.campaign,inv=c.invariants;$('#case-title').textContent=reference;$('#case-body').innerHTML=`${badge(c.state)}<p class="case-reason">${esc(names[c.kind])} · ${esc(inv.classification)}</p><div class="case-grid"><div><small>At stake</small><strong>${money(c.at_risk_paise)}</strong></div><div><small>Reconciled recovery</small><strong class="green">${money(c.recovered_paise)}</strong></div><div><small>Attempts</small><strong>${esc(inv.attempt)}</strong></div><div><small>Contact ceiling</small><strong>${esc(inv.contacts_used)}</strong></div></div><p class="case-reason">${inv.stop_reason?'Stopped: '+esc(inv.stop_reason.replaceAll('_',' ')):'Next: '+esc(inv.next_action||'Awaiting outcome')}${inv.next_due?' · '+esc(new Date(inv.next_due).toLocaleString('en-IN')):''}</p>`;$('#timeline').innerHTML=[...detail.events].reverse().map(e=>`<div class="event ${e.event==='attempt_succeeded'?'win':''}"><time>${esc(new Date(e.at).toLocaleString('en-IN'))}</time><b>${esc(e.event.replaceAll('_',' '))} ${e.channel?'· '+esc(e.channel):''}</b><p>${esc(e.detail)}</p>${e.idempotency_key?`<p>Operation: ${esc(e.idempotency_key)}</p>`:''}</div>`).join('');$('#event-count').textContent=detail.events.length+' events';$('#reply-result').hidden=true;$('#apply-reply').disabled=true;$('#reply-text').value='';if(!$('#case-dialog').open)$('#case-dialog').showModal()}catch(e){notice(e.message,true)}}
$('#close-case').onclick=()=>$('#case-dialog').close();$('#case-dialog').addEventListener('click',e=>{if(e.target===$('#case-dialog')&&e.clientX<$('#case-dialog').getBoundingClientRect().left)$('#case-dialog').close()});
async function readReply(apply){const text=$('#reply-text').value;if(!text.trim())return;const btn=apply?$('#apply-reply'):$('#reply-form button[type=submit]');btn.disabled=true;try{const r=await json(`/api/cases/${encodeURIComponent(activeCase)}/reply?source=${encodeURIComponent(source)}`,{method:'POST',body:JSON.stringify({text,apply,proposal_id:apply?proposalId:null})});proposalId=r.proposal_id;$('#reply-result').hidden=false;$('#reply-result').textContent=`${r.reading.intent.replaceAll('_',' ')} · ${Math.round(r.reading.confidence*100)}% confidence\n${r.reading.reasoning||r.reading.quote}\nRead by ${r.reading.provider} / ${r.reading.model}`+(r.reading.pay_by?'\nPay by '+r.reading.pay_by.slice(0,10):'')+(r.action?'\n\n'+r.action.action.toUpperCase()+': '+r.action.detail:'\n\nProposal only. Apply to record the action.');lastReading=text;$('#apply-reply').disabled=apply;if(apply)await load()}catch(e){$('#reply-result').hidden=false;$('#reply-result').textContent=e.message}finally{btn.disabled=apply}}
$('#reply-form').onsubmit=e=>{e.preventDefault();readReply(false)};$('#reply-text').oninput=()=>{$('#apply-reply').disabled=$('#reply-text').value!==lastReading};$('#apply-reply').onclick=()=>readReply(true);
function setProgress(job){if(job.config)for(const key of ['n','days','seed'])if(job.config[key]!==undefined)$('#batch-form').elements.namedItem(key).value=job.config[key];$('#progress').hidden=false;$('#progress-bar').value=job.progress;$('#progress-percent').textContent=job.progress+'%';$('#progress-text').textContent=job.status==='queued'?'Preparing the book…':'Playing the campaign forward…';$('#batch-submit').disabled=true;$('#batch-submit').textContent='Batch in progress…'}
function schedulePoll(id){if(pollTimer)return;pollTimer=setTimeout(async()=>{pollTimer=null;try{const state=await json('/api/status');const job=state.jobs.find(j=>j.id===id);if(!job)throw Error('Batch not found');if(job.status==='complete'){busy=false;source=id;$('#batch-submit').disabled=false;$('#batch-submit').textContent='Run batch →';$('#progress').hidden=true;await refreshStatus();$('#source').value=source;await load();notice(`Batch complete: ${job.total_cases} synthetic cases evaluated. Select a case to inspect its recovery path.`);page('overview')}else if(['failed','interrupted'].includes(job.status)){busy=false;$('#batch-submit').disabled=false;$('#batch-submit').textContent='Run batch →';$('#progress').hidden=true;notice(job.error||'Batch failed',true)}else{setProgress(job);schedulePoll(id)}}catch(e){busy=false;notice(e.message,true);$('#batch-submit').disabled=false}},1200)}
async function runBatch(args){if(busy){page('lab');return}busy=true;page('lab');notice('');try{const job=await json('/api/batches',{method:'POST',body:JSON.stringify(args)});setProgress(job);schedulePoll(job.id)}catch(e){busy=false;notice(e.message,true)}}
$('#batch-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);runBatch({n:Number(f.get('n')),days:Number(f.get('days')),seed:Number(f.get('seed'))})};$('#quick-run').onclick=$('#empty-run').onclick=()=>runBatch({n:240,days:28,seed:20260905});
$('#csv-form').onsubmit=async e=>{e.preventDefault();const file=$('#csv-file').files[0];if(!file)return;if(file.size>200000){notice('Use a CSV smaller than 200 KB.',true);return}try{const result=await json('/api/import',{method:'POST',body:JSON.stringify({csv:await file.text(),unit:$('#csv-unit').value})});source=result.id;await refreshStatus();await load();$('#csv-result').textContent=result.total_cases+' accepted; '+result.rejected.length+' rejected. '+result.rejected.map(r=>'Line '+r.line+': '+r.error).join(' ');notice('CSV preview campaigns created. Rejected rows are listed in the import panel.');page('campaigns')}catch(err){notice(err.message,true)}};
async function liveRun(execute){const email=$('#delivery-email').checked,sms=$('#delivery-sms').checked;if(execute&&!confirm((email||sms)?'Create up to five TEST links and request '+[email?'email':'',sms?'SMS':''].filter(Boolean).join(' and ')+' notifications to known customers? I confirm these recipients agreed to be contacted. Test notifications may reach real people.':'Create up to five Razorpay TEST payment links without sending messages?'))return;notice('Reading and reconciling the test account…');$('#live-preview').disabled=$('#live-execute').disabled=true;try{const r=await json('/api/live/run',{method:'POST',body:JSON.stringify({execute,max_actions:5,email,sms,confirm_contact:execute&&(email||sms)})});$('#live-result').hidden=false;$('#live-result').textContent=JSON.stringify(r,null,2);notice(r.mode);if(execute){source='live';$('#source').value=source;await load()}}catch(e){notice(e.message,true)}finally{$('#live-preview').disabled=$('#live-execute').disabled=false}}
$('#live-preview').onclick=()=>liveRun(false);$('#live-execute').onclick=()=>liveRun(true);
document.querySelectorAll('.export').forEach(e=>e.onclick=async()=>{if(!source){notice('Select a batch first.');return}try{const r=await api('/api/evidence?source='+encodeURIComponent(source));const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='recovery-'+source+'.jsonl';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice('Audit ledger exported. Keep it with the batch configuration and its simulation label.')}catch(err){notice(err.message,true)}});
$('#credentials').onclick=()=>{const value=prompt('Operator token (only required when configured on the server):');if(value===null)return;token=value.trim();if(token)sessionStorage.setItem('recovery-token',token);else sessionStorage.removeItem('recovery-token');refresh()};
// Startup runs after the connection controls are registered.
